### ISSUE TITLE
Measuring frequencies below 1kHz

### ISSUE THREAD

**Issue by jkapp87lkgc** [antodom/tc_lib#2]
Hello Antonio,
I like your library and am using the latest version, but I am having issues with measuring frequencies below 1kHz.  I am currently attempting to measure frequencies between 50Hz and 150Hz.  When measuring the 1kHz output by using analogWrite, it works correctly.
I am currently using TC1 to do my measurement on Due pin A7. I have also connected an oscilloscope to verify what the frequency is.
I am not certain if I am missing something or if it is an issue with the library. From the forums I have read you stated that it could measure low frequencies.
Any help you can provide is much appreciated.
Thanks
Jeremy

**Comment by antodom** [comment]
Which capture window are you setting?, maybe that's the problem. I advice you to set a capture window twice the period you want to measure. In any case, if that's not the problem, I would need more information to try to diagnose what is happening and to be of any help. To have a code example and  an explanation of the hardware set would help.

Best.
