### ISSUE TITLE
tc_defs.h doesn't compile with GCC 6 (with solution)

### ISSUE THREAD

**Issue by EmbeddedG** [antodom/tc_lib#3]
I have to use newer GCC than the stock Arduino toolchain to use C++14 features. Older GCCs permitted reinterpret_cast in initialization of static constexpr members, but as I read it is against the C++ standard and newer GCC and clang versions doesn't allow this, thus they fail on this code:
```
    template<> struct tc_info< \
      timer_ids::TIMER_TC##timer_id \
    > \
    { \
      static constexpr Tc* tc_p = tc_x; \
      static constexpr const uint32_t channel = channel_x; \
      static constexpr const IRQn_Type irq = TC##timer_id##_IRQn; \
    };
```
with errors like this: `sam3x8e.h: error: reinterpret_cast from integer to pointer`
The problem is with:
``static constexpr Tc* tc_p = tc_x;``

The solution I found is to change tc_p to a static inline function, as suggested [in this comment](https://stackoverflow.com/questions/10369606/constexpr-pointer-value#comment13364565_10369606):
``static inline Tc* tc_p() {return tc_x; }``
and replace every reference with a function call.

Sorry for not providing a patch, on windows I don't remember the proper way to produce one.

**Comment by antodom** [comment]
Thank you for your comment EmbeddedG, I will correct this as soon as I can.

**Comment by antodom** [comment]
Thank you again for your comment EmbeddedG, after considering several solutions, I think the best approach is the one you have suggested. I have already applied it to the project.

I beg you sorry for the delay. 
Best regards.

**Comment by EmbeddedG** [comment]
No problem for the delay, thank you for applying my solution, I'm glad I could help!
