### ISSUE TITLE
capture::lock() and capture::unlock not compiling

### ISSUE THREAD

**Issue by balinthanula** [antodom/tc_lib#5]
Hey Antonio,

I really like your library and im using it for an all electric instrument panel project for my car (instead of the mechanical gauges). lock() tc_lib.h:199 and unlock() tc_lib.h:205 are not compiling if used in the code. is_unset() and is_stopped() are only declared for is_stopped(uint32_t the_status) and is_unset(uint32_t the_status). 

Best regards
Bálint

**Comment by antodom** [comment]
Hi there again Bálint,

I have modified the library in order to solve this problem. Now there are versions of is_unset(), is_stopped() and is_overrun() without arguments. Please, check and tell me.

I hope it helps.
